{
  "results": [
    {
      "source": {
        "path": "/src/github.sbom.spdx.json",
        "type": "sbom"
      },
      "packages": [
        {
          "package": {
            "name": "jinja2",
            "version": "2.10.1",
            "ecosystem": "PyPI",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2023-11-08T04:03:28Z",
              "published": "2021-03-19T21:28:05Z",
              "schema_version": "1.6.0",
              "id": "GHSA-g3rq-g295-4j3m",
              "aliases": [
                "CVE-2020-28493",
                "PYSEC-2021-66",
                "SNYK-PYTHON-JINJA2-1012994"
              ],
              "summary": "Regular Expression Denial of Service (ReDoS) in Jinja2",
              "details": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDOS vulnerability of the regex is mainly due to the sub-pattern [a-zA-Z0-9._-]+.[a-zA-Z0-9._-]+ This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.11.3"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0",
                    "2.0rc1",
                    "2.1",
                    "2.1.1",
                    "2.10",
                    "2.10.1",
                    "2.10.2",
                    "2.10.3",
                    "2.11.0",
                    "2.11.1",
                    "2.11.2",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8",
                    "2.8.1",
                    "2.9",
                    "2.9.1",
                    "2.9.2",
                    "2.9.3",
                    "2.9.4",
                    "2.9.5",
                    "2.9.6"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/03/GHSA-g3rq-g295-4j3m/GHSA-g3rq-g295-4j3m.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "jinja2.utils.urlize"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28493"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/pull/1343"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/commit/15ef8f09b659f9100610583938005a7a10472d4d"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/pallets/jinja"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/"
                },
                {
                  "type": "WEB",
                  "url": "https://security.gentoo.org/glsa/202107-19"
                },
                {
                  "type": "WEB",
                  "url": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-400"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-03-13T01:08:09Z",
                "nvd_published_at": "2021-02-01T20:15:00Z",
                "severity": "MODERATE"
              }
            },
            {
              "modified": "2023-11-08T04:03:28Z",
              "published": "2021-02-01T20:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2021-66",
              "aliases": [
                "CVE-2020-28493",
                "GHSA-g3rq-g295-4j3m",
                "SNYK-PYTHON-JINJA2-1012994"
              ],
              "details": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation. This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "jinja2",
                    "purl": "pkg:pypi/jinja2"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "2.11.3"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "2.0rc1",
                    "2.0",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.3.1",
                    "2.4",
                    "2.4.1",
                    "2.5",
                    "2.5.1",
                    "2.5.2",
                    "2.5.3",
                    "2.5.4",
                    "2.5.5",
                    "2.6",
                    "2.7",
                    "2.7.1",
                    "2.7.2",
                    "2.7.3",
                    "2.8",
                    "2.8.1",
                    "2.9",
                    "2.9.1",
                    "2.9.2",
                    "2.9.3",
                    "2.9.4",
                    "2.9.5",
                    "2.9.6",
                    "2.10",
                    "2.10.1",
                    "2.10.2",
                    "2.10.3",
                    "2.11.0",
                    "2.11.1",
                    "2.11.2"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/jinja2/PYSEC-2021-66.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pallets/jinja/pull/1343"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-g3rq-g295-4j3m"
                }
              ]
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-g3rq-g295-4j3m",
                "PYSEC-2021-66"
              ]
            }
          ]
        },
        {
          "package": {
            "name": "pyyaml",
            "version": "3.10",
            "ecosystem": "PyPI",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2023-11-08T04:02:41Z",
              "published": "2021-04-20T16:14:24Z",
              "schema_version": "1.6.0",
              "id": "GHSA-6757-jp84-gxfx",
              "aliases": [
                "CVE-2020-1747",
                "PYSEC-2020-96"
              ],
              "summary": "Improper Input Validation in PyYAML",
              "details": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyyaml",
                    "purl": "pkg:pypi/pyyaml"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "5.3.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "3.01",
                    "3.02",
                    "3.03",
                    "3.04",
                    "3.05",
                    "3.06",
                    "3.07",
                    "3.08",
                    "3.09",
                    "3.10",
                    "3.11",
                    "3.12",
                    "3.13",
                    "3.13b1",
                    "3.13rc1",
                    "4.2b1",
                    "4.2b2",
                    "4.2b4",
                    "5.1",
                    "5.1.1",
                    "5.1.2",
                    "5.1b1",
                    "5.1b3",
                    "5.1b5",
                    "5.1b7",
                    "5.2",
                    "5.2b1",
                    "5.3",
                    "5.3b1"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/04/GHSA-6757-jp84-gxfx/GHSA-6757-jp84-gxfx.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "yaml.load",
                      "yaml.full_load",
                      "yaml.FullLoader"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-1747"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/pull/386"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0"
                },
                {
                  "type": "WEB",
                  "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/yaml/pyyaml"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/"
                },
                {
                  "type": "WEB",
                  "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html"
                },
                {
                  "type": "WEB",
                  "url": "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-20"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-04-07T22:29:00Z",
                "nvd_published_at": "2020-03-24T15:15:00Z",
                "severity": "CRITICAL"
              }
            },
            {
              "modified": "2023-11-08T04:02:26Z",
              "published": "2021-03-25T21:26:26Z",
              "schema_version": "1.6.0",
              "id": "GHSA-8q59-q68h-6hv4",
              "aliases": [
                "CVE-2020-14343",
                "PYSEC-2021-142"
              ],
              "summary": "Improper Input Validation in PyYAML",
              "details": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyyaml",
                    "purl": "pkg:pypi/pyyaml"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "5.4"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "3.01",
                    "3.02",
                    "3.03",
                    "3.04",
                    "3.05",
                    "3.06",
                    "3.07",
                    "3.08",
                    "3.09",
                    "3.10",
                    "3.11",
                    "3.12",
                    "3.13",
                    "3.13b1",
                    "3.13rc1",
                    "4.2b1",
                    "4.2b2",
                    "4.2b4",
                    "5.1",
                    "5.1.1",
                    "5.1.2",
                    "5.1b1",
                    "5.1b3",
                    "5.1b5",
                    "5.1b7",
                    "5.2",
                    "5.2b1",
                    "5.3",
                    "5.3.1",
                    "5.3b1",
                    "5.4b1",
                    "5.4b2"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/03/GHSA-8q59-q68h-6hv4/GHSA-8q59-q68h-6hv4.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "yaml.constructor.FullConstructor",
                      "yaml.constructor.UnsafeConstructor"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-14343"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/SeldonIO/seldon-core/issues/2252"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/issues/420"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
                },
                {
                  "type": "WEB",
                  "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/yaml/pyyaml"
                },
                {
                  "type": "WEB",
                  "url": "https://pypi.org/project/PyYAML/"
                },
                {
                  "type": "WEB",
                  "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                },
                {
                  "type": "WEB",
                  "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-20"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2021-03-25T21:15:23Z",
                "nvd_published_at": "2021-02-09T21:15:00Z",
                "severity": "CRITICAL"
              }
            },
            {
              "modified": "2023-11-08T03:59:15Z",
              "published": "2019-01-04T17:45:26Z",
              "schema_version": "1.6.0",
              "id": "GHSA-rprw-h62v-c2w7",
              "aliases": [
                "CVE-2017-18342",
                "PYSEC-2018-49"
              ],
              "summary": "PyYAML insecurely deserializes YAML strings leading to arbitrary code execution",
              "details": "In PyYAML before 4.1, the `yaml.load()` API could execute arbitrary code. In other words, `yaml.safe_load` is not used.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyyaml",
                    "purl": "pkg:pypi/pyyaml"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "4.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "3.01",
                    "3.02",
                    "3.03",
                    "3.04",
                    "3.05",
                    "3.06",
                    "3.07",
                    "3.08",
                    "3.09",
                    "3.10",
                    "3.11",
                    "3.12",
                    "3.13",
                    "3.13b1",
                    "3.13rc1"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2019/01/GHSA-rprw-h62v-c2w7/GHSA-rprw-h62v-c2w7.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "yaml.load",
                      "yaml.dump",
                      "safe_dump_all",
                      "safe_dump",
                      "yaml.CSafeLoader",
                      "yaml.CLoader",
                      "yaml.CSafeDumper",
                      "yaml.CDumper",
                      "yaml.SafeDumper",
                      "yaml.Dumper",
                      "yaml.SafeLoader",
                      "yaml.Loader"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2017-18342"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/marshmallow-code/apispec/issues/278"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/issues/193"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/pull/74"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/commit/7b68405c81db889f83c32846462b238ccae5be80"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/yaml/pyyaml"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/blob/master/CHANGES"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JEX7IPV5P2QJITAMA5Z63GQCZA5I6NVZ/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KSQQMRUQSXBSUXLCRD3TSZYQ7SEZRKCE/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M6JCFGEIEOFMWWIXGHSELMKQDD4CV2BA/"
                },
                {
                  "type": "WEB",
                  "url": "https://security.gentoo.org/glsa/202003-45"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-502"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2020-06-16T21:55:26Z",
                "nvd_published_at": null,
                "severity": "CRITICAL"
              }
            },
            {
              "modified": "2023-11-08T03:59:15Z",
              "published": "2018-06-27T12:29:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2018-49",
              "aliases": [
                "CVE-2017-18342",
                "GHSA-rprw-h62v-c2w7"
              ],
              "details": "In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if used with untrusted data. The load() function has been deprecated in version 5.1 and the 'UnsafeLoader' has been introduced for backward compatibility with the function.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyyaml",
                    "purl": "pkg:pypi/pyyaml"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "5.1"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "3.01",
                    "3.02",
                    "3.03",
                    "3.04",
                    "3.05",
                    "3.06",
                    "3.07",
                    "3.08",
                    "3.09",
                    "3.10",
                    "3.11",
                    "3.12",
                    "3.13",
                    "3.13b1",
                    "3.13rc1",
                    "4.2b1",
                    "4.2b2",
                    "4.2b4",
                    "5.1b1",
                    "5.1b3",
                    "5.1b5",
                    "5.1b7"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pyyaml/PYSEC-2018-49.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/pull/74"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/blob/master/CHANGES"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M6JCFGEIEOFMWWIXGHSELMKQDD4CV2BA/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KSQQMRUQSXBSUXLCRD3TSZYQ7SEZRKCE/"
                },
                {
                  "type": "WEB",
                  "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JEX7IPV5P2QJITAMA5Z63GQCZA5I6NVZ/"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation"
                },
                {
                  "type": "REPORT",
                  "url": "https://github.com/marshmallow-code/apispec/issues/278"
                },
                {
                  "type": "REPORT",
                  "url": "https://github.com/yaml/pyyaml/issues/193"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://security.gentoo.org/glsa/202003-45"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-rprw-h62v-c2w7"
                }
              ]
            },
            {
              "modified": "2023-11-08T04:02:26Z",
              "published": "2021-02-09T21:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2021-142",
              "aliases": [
                "CVE-2020-14343",
                "GHSA-8q59-q68h-6hv4"
              ],
              "details": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "pyyaml",
                    "purl": "pkg:pypi/pyyaml"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "5.4"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "3.01",
                    "3.02",
                    "3.03",
                    "3.04",
                    "3.05",
                    "3.06",
                    "3.07",
                    "3.08",
                    "3.09",
                    "3.10",
                    "3.11",
                    "3.12",
                    "3.13",
                    "3.13b1",
                    "3.13rc1",
                    "4.2b1",
                    "4.2b2",
                    "4.2b4",
                    "5.1",
                    "5.1.1",
                    "5.1.2",
                    "5.1b1",
                    "5.1b3",
                    "5.1b5",
                    "5.1b7",
                    "5.2",
                    "5.2b1",
                    "5.3",
                    "5.3.1",
                    "5.3b1",
                    "5.4b1",
                    "5.4b2"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pyyaml/PYSEC-2021-142.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "REPORT",
                  "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
                },
                {
                  "type": "ADVISORY",
                  "url": "https://github.com/advisories/GHSA-8q59-q68h-6hv4"
                }
              ]
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-6757-jp84-gxfx"
              ]
            },
            {
              "ids": [
                "GHSA-8q59-q68h-6hv4",
                "PYSEC-2021-142"
              ]
            },
            {
              "ids": [
                "GHSA-rprw-h62v-c2w7",
                "PYSEC-2018-49"
              ]
            }
          ]
        },
        {
          "package": {
            "name": "tornado",
            "version": "3.1.1",
            "ecosystem": "PyPI",
            "commit": ""
          },
          "vulnerabilities": [
            {
              "modified": "2023-11-12T05:24:51Z",
              "published": "2023-05-25T12:30:16Z",
              "schema_version": "1.6.0",
              "id": "GHSA-hj3f-6gcp-jg8j",
              "aliases": [
                "CVE-2023-28370",
                "PYSEC-2023-75"
              ],
              "summary": "Open redirect in Tornado",
              "details": "Open redirect vulnerability in Tornado versions 6.3.1 and earlier allows a remote unauthenticated attacker to redirect a user to an arbitrary web site and conduct a phishing attack by having user access a specially crafted URL.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "tornado",
                    "purl": "pkg:pypi/tornado"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "6.3.2"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.2",
                    "1.0",
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "2.0",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.4",
                    "2.4.1",
                    "3.0",
                    "3.0.1",
                    "3.0.2",
                    "3.1",
                    "3.1.1",
                    "3.2",
                    "3.2.1",
                    "3.2.2",
                    "4.0",
                    "4.0.1",
                    "4.0.2",
                    "4.1",
                    "4.1b2",
                    "4.2",
                    "4.2.1",
                    "4.2b1",
                    "4.3",
                    "4.3b1",
                    "4.3b2",
                    "4.4",
                    "4.4.1",
                    "4.4.2",
                    "4.4.3",
                    "4.4b1",
                    "4.5",
                    "4.5.1",
                    "4.5.2",
                    "4.5.3",
                    "4.5b1",
                    "4.5b2",
                    "5.0",
                    "5.0.1",
                    "5.0.2",
                    "5.0a1",
                    "5.0b1",
                    "5.1",
                    "5.1.1",
                    "5.1b1",
                    "6.0",
                    "6.0.1",
                    "6.0.2",
                    "6.0.3",
                    "6.0.4",
                    "6.0a1",
                    "6.0b1",
                    "6.1",
                    "6.1b1",
                    "6.1b2",
                    "6.2",
                    "6.2b1",
                    "6.2b2",
                    "6.3",
                    "6.3.1",
                    "6.3b1"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/05/GHSA-hj3f-6gcp-jg8j/GHSA-hj3f-6gcp-jg8j.json"
                  },
                  "ecosystem_specific": {
                    "affected_functions": [
                      "tornado.web.StaticFileHandler.validate_absolute_path"
                    ]
                  }
                }
              ],
              "severity": [
                {
                  "type": "CVSS_V3",
                  "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
                }
              ],
              "references": [
                {
                  "type": "ADVISORY",
                  "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28370"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/tornadoweb/tornado/commit/32ad07c54e607839273b4e1819c347f5c8976b2f"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/pypa/advisory-database/tree/main/vulns/tornado/PYSEC-2023-75.yaml"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/tornadoweb/tornado"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/tornadoweb/tornado/releases/tag/v6.3.2"
                },
                {
                  "type": "WEB",
                  "url": "https://jvn.jp/en/jp/JVN45127776/"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-601"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2023-05-25T17:00:25Z",
                "nvd_published_at": "2023-05-25T10:15:09Z",
                "severity": "MODERATE"
              }
            },
            {
              "modified": "2023-08-14T21:48:29Z",
              "published": "2023-08-14T21:34:17Z",
              "schema_version": "1.6.0",
              "id": "GHSA-qppv-j76h-2rpx",
              "summary": "Tornado vulnerable to HTTP request smuggling via improper parsing of `Content-Length` fields and chunk lengths",
              "details": "## Summary\nTornado interprets `-`, `+`, and `_` in chunk length and `Content-Length` values, which are not allowed by the HTTP RFCs. This can result in request smuggling when Tornado is deployed behind certain proxies that interpret those non-standard characters differently. This is known to apply to older versions of haproxy, although the current release is not affected.\n\n## Details\nTornado uses the `int` constructor to parse the values of `Content-Length` headers and chunk lengths in the following locations:\n### `tornado/http1connection.py:445`\n```python3\n            self._expected_content_remaining = int(headers[\"Content-Length\"])\n```\n### `tornado/http1connection.py:621`\n```python3\n                content_length = int(headers[\"Content-Length\"])  # type: Optional[int]\n```\n### `tornado/http1connection.py:671`\n```python3\n            chunk_len = int(chunk_len_str.strip(), 16)\n```\nBecause `int(\"0_0\") == int(\"+0\") == int(\"-0\") == int(\"0\")`, using the `int` constructor to parse and validate strings that should contain only ASCII digits is not a good strategy. \n\n",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "tornado",
                    "purl": "pkg:pypi/tornado"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "6.3.3"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.2",
                    "1.0",
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "2.0",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.4",
                    "2.4.1",
                    "3.0",
                    "3.0.1",
                    "3.0.2",
                    "3.1",
                    "3.1.1",
                    "3.2",
                    "3.2.1",
                    "3.2.2",
                    "4.0",
                    "4.0.1",
                    "4.0.2",
                    "4.1",
                    "4.1b2",
                    "4.2",
                    "4.2.1",
                    "4.2b1",
                    "4.3",
                    "4.3b1",
                    "4.3b2",
                    "4.4",
                    "4.4.1",
                    "4.4.2",
                    "4.4.3",
                    "4.4b1",
                    "4.5",
                    "4.5.1",
                    "4.5.2",
                    "4.5.3",
                    "4.5b1",
                    "4.5b2",
                    "5.0",
                    "5.0.1",
                    "5.0.2",
                    "5.0a1",
                    "5.0b1",
                    "5.1",
                    "5.1.1",
                    "5.1b1",
                    "6.0",
                    "6.0.1",
                    "6.0.2",
                    "6.0.3",
                    "6.0.4",
                    "6.0a1",
                    "6.0b1",
                    "6.1",
                    "6.1b1",
                    "6.1b2",
                    "6.2",
                    "6.2b1",
                    "6.2b2",
                    "6.3",
                    "6.3.1",
                    "6.3.2",
                    "6.3b1"
                  ],
                  "database_specific": {
                    "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2023/08/GHSA-qppv-j76h-2rpx/GHSA-qppv-j76h-2rpx.json"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://github.com/tornadoweb/tornado/security/advisories/GHSA-qppv-j76h-2rpx"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/tornadoweb/tornado/commit/b7a5dd29bb02950303ae96055082c12a1ea0a4fe"
                },
                {
                  "type": "PACKAGE",
                  "url": "https://github.com/tornadoweb/tornado"
                }
              ],
              "database_specific": {
                "cwe_ids": [
                  "CWE-444"
                ],
                "github_reviewed": true,
                "github_reviewed_at": "2023-08-14T21:34:17Z",
                "nvd_published_at": null,
                "severity": "MODERATE"
              }
            },
            {
              "modified": "2023-11-08T03:57:47Z",
              "published": "2020-01-24T18:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2020-213",
              "aliases": [
                "CVE-2014-9720"
              ],
              "details": "Tornado before 3.2.2 sends arbitrary responses that contain a fixed CSRF token and may be sent with HTTP compression, which makes it easier for remote attackers to conduct a BREACH attack and determine this token via a series of crafted requests.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "tornado",
                    "purl": "pkg:pypi/tornado"
                  },
                  "ranges": [
                    {
                      "type": "GIT",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "1c36307463b1e8affae100bf9386948e6c1b2308"
                        }
                      ],
                      "repo": "https://github.com/tornadoweb/tornado"
                    },
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "3.2.2"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.2",
                    "1.0",
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "2.0",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.4",
                    "2.4.1",
                    "3.0",
                    "3.0.1",
                    "3.0.2",
                    "3.1",
                    "3.1.1",
                    "3.2",
                    "3.2.1"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/tornado/PYSEC-2020-213.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "FIX",
                  "url": "https://github.com/tornadoweb/tornado/commit/1c36307463b1e8affae100bf9386948e6c1b2308"
                },
                {
                  "type": "REPORT",
                  "url": "https://bugzilla.novell.com/show_bug.cgi?id=930362"
                },
                {
                  "type": "WEB",
                  "url": "http://openwall.com/lists/oss-security/2015/05/19/4"
                },
                {
                  "type": "REPORT",
                  "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1222816"
                },
                {
                  "type": "WEB",
                  "url": "http://www.tornadoweb.org/en/stable/releases/v3.2.2.html"
                }
              ]
            },
            {
              "modified": "2023-11-08T04:12:10Z",
              "published": "2023-05-25T10:15:00Z",
              "schema_version": "1.6.0",
              "id": "PYSEC-2023-75",
              "aliases": [
                "CVE-2023-28370",
                "GHSA-hj3f-6gcp-jg8j"
              ],
              "details": "Open redirect vulnerability in Tornado versions 6.3.1 and earlier allows a remote unauthenticated attacker to redirect a user to an arbitrary web site and conduct a phishing attack by having user access a specially crafted URL.",
              "affected": [
                {
                  "package": {
                    "ecosystem": "PyPI",
                    "name": "tornado",
                    "purl": "pkg:pypi/tornado"
                  },
                  "ranges": [
                    {
                      "type": "ECOSYSTEM",
                      "events": [
                        {
                          "introduced": "0"
                        },
                        {
                          "fixed": "6.3.2"
                        }
                      ]
                    }
                  ],
                  "versions": [
                    "0.2",
                    "1.0",
                    "1.1",
                    "1.1.1",
                    "1.2",
                    "1.2.1",
                    "2.0",
                    "2.1",
                    "2.1.1",
                    "2.2",
                    "2.2.1",
                    "2.3",
                    "2.4",
                    "2.4.1",
                    "3.0",
                    "3.0.1",
                    "3.0.2",
                    "3.1",
                    "3.1.1",
                    "3.2",
                    "3.2.1",
                    "3.2.2",
                    "4.0",
                    "4.0.1",
                    "4.0.2",
                    "4.1",
                    "4.1b2",
                    "4.2",
                    "4.2.1",
                    "4.2b1",
                    "4.3",
                    "4.3b1",
                    "4.3b2",
                    "4.4",
                    "4.4.1",
                    "4.4.2",
                    "4.4.3",
                    "4.4b1",
                    "4.5",
                    "4.5.1",
                    "4.5.2",
                    "4.5.3",
                    "4.5b1",
                    "4.5b2",
                    "5.0",
                    "5.0.1",
                    "5.0.2",
                    "5.0a1",
                    "5.0b1",
                    "5.1",
                    "5.1.1",
                    "5.1b1",
                    "6.0",
                    "6.0.1",
                    "6.0.2",
                    "6.0.3",
                    "6.0.4",
                    "6.0a1",
                    "6.0b1",
                    "6.1",
                    "6.1b1",
                    "6.1b2",
                    "6.2",
                    "6.2b1",
                    "6.2b2",
                    "6.3",
                    "6.3.1",
                    "6.3b1"
                  ],
                  "database_specific": {
                    "source": "https://github.com/pypa/advisory-database/blob/main/vulns/tornado/PYSEC-2023-75.yaml"
                  }
                }
              ],
              "references": [
                {
                  "type": "WEB",
                  "url": "https://jvn.jp/en/jp/JVN45127776/"
                },
                {
                  "type": "WEB",
                  "url": "https://github.com/tornadoweb/tornado/releases/tag/v6.3.2"
                }
              ]
            }
          ],
          "groups": [
            {
              "ids": [
                "GHSA-hj3f-6gcp-jg8j",
                "PYSEC-2023-75"
              ]
            },
            {
              "ids": [
                "GHSA-qppv-j76h-2rpx"
              ]
            },
            {
              "ids": [
                "PYSEC-2020-213"
              ]
            }
          ]
        }
      ]
    }
  ]
}
